const spots=[
 {name:'美國小鎮大街',icon:'🏘️',hint:'留意街道兩旁的建築、音樂和遊人的神情。',prompts:[['最先吸引你目光的是甚麼？','近處、中間和遠處各有甚麼？','遊人正在做甚麼？'],['你可能聽見哪些聲音？','陽光照在建築上，顏色有甚麼變化？','看見遠方城堡，你心裏有何期待？'],['用「踏進樂園，我看見……」開始。','用「有的……有的……」寫遊人的動作。','試加一個比喻，把街道寫得更生動。']]},
 {name:'幻想世界',icon:'🎠',hint:'試用顏色、聲音和比喻，寫出童話般的氣氛。',prompts:[['旋轉木馬有甚麼顏色和裝飾？','木馬和遊人正在怎樣移動？','四周還有哪些童話般的景物？'],['閉上眼想像：音樂是輕快還是柔和？','乘坐木馬時，風和速度帶來甚麼感覺？','這個畫面令你聯想到甚麼？'],['用「沿着小路前行，我們來到……」定位。','以「木馬隨着音樂……」描寫動態。','用「彷彿」寫一個聯想句。']]},
 {name:'探險世界',icon:'🌿',hint:'寫出你乘坐或遊覽時的動作，讓畫面動起來。',prompts:[['你看到哪些植物、水流和建築？','小船由哪裏駛向哪裏？','前、中、後景有甚麼不同？'],['水聲、船聲和遊人的聲音可能怎樣？','茂密植物令環境顯得怎樣？','如果小船突然轉彎，你有何反應？'],['用「離開……後，我們走進……」過渡。','選兩個動詞：駛過、濺起、搖晃、穿過。','不用只寫「刺激」，寫出你的表情或動作。']]},
 {name:'明日世界',icon:'🚀',hint:'把燈光、速度或聲音寫清楚，再補上真實感受。',prompts:[['天空和燈光各是甚麼顏色？','哪些線條或建築帶有未來感？','人群向哪裏移動？'],['天色變暗後，燈光令氣氛有何改變？','想像機器運轉時有甚麼聲音？','這是旅程尾站，你的心情有何轉變？'],['用「最後，我們穿過人群，來到……」定位。','把燈光比作星星、彩帶或其他事物。','加入「雖然……但是……」寫離開前的心情。']]},
 {name:'魔雪奇緣世界',icon:'❄️',hint:'觀察雪山、城堡和村莊，再寫人物參與活動時的反應。',prompts:[['雪山、鐘樓和村莊分布在哪裏？','遊人正前往哪一項活動？','畫面以哪些冷暖顏色為主？'],['走進阿德爾村莊時，你先看見甚麼？','雪橇開動時，人物有何動作？','室內和室外的氣氛有何不同？'],['用「沿着湖邊走，我們來到……」定位。','選用「駛進、滑過、歡呼」描寫活動。','用一個比喻寫出冰雪景色。']]},
 {name:'灰熊山谷',icon:'🐻',hint:'留意礦山小鎮、礦車和噴泉，把速度及人物反應寫具體。',prompts:[['礦山、木屋和路軌各在甚麼位置？','礦車正怎樣移動？','遊人正在參與甚麼活動？'],['礦車衝出山洞時，你可能聽見甚麼？','噴泉忽然冒出，人物有何反應？','荒野小鎮給你甚麼感覺？'],['用「穿過山路，我們來到……」定位。','選用「衝出、轉彎、濺起」描寫動態。','寫出表情或身體反應，不只寫「刺激」。']]}
];
const quizData=[{q:'哪一句最能顯示位置改變？',o:['樂園裏有很多遊樂設施。','走過小鎮大街，我們來到色彩繽紛的幻想世界。'],a:1,e:'「走過……來到……」交代了移動路線。'},{q:'哪一句符合「一步一景」？',o:['我很開心，今天真的很開心。','離開旋轉木馬後，我們沿小路走到探險世界，眼前盡是茂密的樹木。'],a:1,e:'位置由旋轉木馬移到探險世界，眼前景物亦隨之改變。'},{q:'步移法中的景物應該怎樣安排？',o:['跟隨遊覽次序描寫。','把所有景物隨意混在一起。'],a:0,e:'跟着腳步順序寫，讀者才能清楚地「一起遊覽」。'}];
const sceneObjects=[
 [{x:52,y:30,t:'遠方景物',n:'城堡、塔尖、旗幟',q:'它令你聯想到哪一個童話世界？'},{x:18,y:50,t:'街道景物',n:'店舖、櫥窗、花籃、路燈',q:'你會先寫近處還是遠處？為甚麼？'},{x:76,y:68,t:'人物與環境',n:'遊人、嬰兒車、路軌、廣場',q:'遊人可能正在做甚麼？'}],
 [{x:50,y:42,t:'遊樂設施',n:'旋轉木馬、木馬、燈飾、圍欄',q:'木馬可能怎樣移動？'},{x:24,y:68,t:'廣場景物',n:'花圃、花朵、石磚、拱門',q:'你可以從哪些顏色開始觀察？'},{x:78,y:55,t:'人物與建築',n:'遊人、孩子、尖頂小屋、城樓',q:'人物的表情可能是怎樣的？'}],
 [{x:70,y:58,t:'河道景物',n:'小船、河道、水花、木欄',q:'小船由哪裏駛向哪裏？'},{x:28,y:36,t:'植物景物',n:'棕櫚樹、樹葉、藤蔓、花朵',q:'前景和遠景的植物有何不同？'},{x:55,y:25,t:'山谷景物',n:'瀑布、岩石、吊橋、河水',q:'除了眼睛，你還可以用哪種感官觀察？'}],
 [{x:54,y:40,t:'未來建築',n:'塔樓、圓頂、天橋、廣場',q:'哪些外形令你想到未來世界？'},{x:82,y:32,t:'燈光景物',n:'霓虹燈、光環、燈柱、晚霞',q:'天色和燈光的顏色有何不同？'},{x:25,y:67,t:'人物與道路',n:'遊人、步道、花圃、欄杆',q:'人物正朝哪個方向前進？'}],
 [{x:24,y:38,t:'村莊景物',n:'鐘樓、湖面、彩色小屋',q:'近處和遠處的建築有甚麼不同？'},{x:62,y:24,t:'冰雪景物',n:'雪山、冰宮、瀑布',q:'哪些顏色營造冰雪世界的感覺？'},{x:72,y:68,t:'人物與道路',n:'遊人、石路、旗幟',q:'遊人正朝哪一項活動前進？'}],
 [{x:62,y:30,t:'礦山景物',n:'礦山、山洞、路軌',q:'路軌由哪裏伸展到哪裏？'},{x:25,y:58,t:'小鎮景物',n:'木屋、水塔、木牌',q:'這些建築帶來甚麼時代感？'},{x:76,y:70,t:'人物與設施',n:'礦車、遊人、噴泉',q:'人物和設施正在怎樣移動？'}]
];
const sceneImages=['scene-main-street.png','scene-fantasy.png','scene-adventure.png','scene-future.png',null,null];
const activities=[
 [{t:'沿小鎮大街前行',n:'大街、路軌、店舖',v:'步行、張望、拍照',q:'同行的人一邊前行，一邊做甚麼？',img:'Disneyland_Hong_Kong_-_Main_Street_USA_IMG_5514.JPG',credit:'Deror avi · CC BY-SA',p:'45%'},{t:'乘坐小鎮車',n:'古董車、車廂、路軌',v:'登上、坐下、駛過',q:'車輛開動前後，人物有甚麼動作？',img:'Hong_Kong_Disneyland_Main_Street_Vehicles_Taxi.jpg',credit:'Jeremy Thompson · CC BY 2.0',p:'62%'},{t:'欣賞巡遊表演',n:'花車、表演者、觀眾',v:'巡遊、揮手、拍掌',q:'表演者和觀眾的動作有何不同？',img:'HK_Disneyland_parade_4_by_Dave_Q.jpg',credit:'Dave Q · CC BY 2.0',p:'20%'}],
 [{t:'乘坐旋轉木馬',n:'木馬、圍欄、燈飾',v:'跨上、升降、旋轉',q:'機動遊戲開始後，你的身體和表情怎樣？',img:'HKDL_CINDERELLA_CAROUSEL.jpg',credit:'Thwong terry · CC BY 3.0',p:'54%'},{t:'遊覽小小世界',n:'彩色外牆、鐘樓、小船',v:'登船、前進、張望',q:'小船駛進室內後，你會留意哪些景物？',img:"HK_Disneyland_It's_a_small_world.JPG",credit:'AdeKaka · Wikimedia Commons',p:'18%'},{t:'乘坐樂園鐵路',n:'月台、火車、路軌',v:'候車、登上、駛離',q:'火車進站時，月台上的人有甚麼反應？',img:'HK_Disneyland_Fantasyland_Station_b.jpg',credit:'Wikimedia Commons · CC',p:'82%'}],
 [{t:'乘船探險',n:'小船、河道、水花',v:'登船、駛過、搖晃',q:'小船遇到急流時，遊人有何反應？',img:'HKDL_JUNGLE_RIVER_CRUISE.jpg',credit:'Thwong terry · CC BY 3.0',p:'70%'},{t:'登上樹屋',n:'樹屋、樓梯、木橋',v:'攀上、扶着、俯瞰',q:'走到高處時，你看見甚麼？身體有何動作？',img:"HKDL_TARZAN'S_TREEHOUSE.jpg",credit:'Thwong terry · Wikimedia Commons',p:'48%'},{t:'沿河岸探險',n:'河岸、棕櫚樹、木欄',v:'走近、穿過、抬頭',q:'由近至遠，河岸的景物有甚麼變化？',img:'HKDL_Adventureland.JPG',credit:'Noahudlis · Wikimedia Commons',p:'25%'}],
 [{t:'體驗太空山',n:'太空站、座椅、安全帶',v:'扣好、加速、轉彎',q:'速度改變時，你的手腳和聲音有何反應？',img:'HK_Disneyland_Space_Mountain.jpg',credit:'Eagle4life69 · Wikimedia Commons',p:'58%'},{t:'欣賞未來世界夜景',n:'燈柱、光環、夜空',v:'閃爍、變換、照亮',q:'天色轉暗後，人群如何觀看四周？',img:'Disneyland_Hong_Kong_-_Tommorowland_at_night_IMG_5523.JPG',credit:'Deror avi · CC BY-SA',p:'78%'},{t:'穿越未來廣場',n:'廣場、天橋、塔樓',v:'穿過、仰望、走向',q:'大家急着走向哪裏？途中做了甚麼？',img:'Disneyland_Hong_Kong_-_Tommorowland_IMG_5413.JPG',credit:'Deror avi · CC BY-SA',p:'28%'}],
 [{t:'乘坐魔雪奇幻之旅',n:'小船、冰宮、藍色冰柱',v:'登船、駛進、仰望',q:'小船駛進冰宮後，四周的燈光和景物有甚麼變化？',img:'https://files.toodaylab.com/2023/11/DisneyHK_Frozen_20231122155656_00.jpg',page:'https://www.toodaylab.com/82410',credit:'香港迪士尼樂園圖片 · 理想生活實驗室（CC BY-NC-ND 4.0）',p:'50%'},{t:'乘坐雪嶺滑雪橇',n:'雪橇、山坡、木橋',v:'登上、滑過、加速',q:'雪橇加速時，人物的身體和表情有何變化？',img:"Wandering_Oaken's_Sliding_Sleighs,_Hong_Kong_Disneyland_2023.jpg",credit:'Tombus20032000 · CC BY-SA 4.0',p:'62%'},{t:'遊覽阿德爾村莊',n:'鐘樓、湖面、彩色小屋',v:'漫步、仰望、拍照',q:'由湖邊走向村莊時，眼前景物怎樣改變？',img:'World_of_Frozen,_Hong_Kong_Disneyland_2023.jpg',credit:'Tombus20032000 · CC BY-SA 4.0',p:'42%'}],
 [{t:'乘坐灰熊山極速礦車',n:'礦車、山洞、路軌',v:'衝出、倒後、轉彎',q:'礦車突然改變方向時，人物有何反應？',img:'Big_Grizzly_Mountain_Runaway_Mine_Cars_IMG_5488.JPG',credit:'Deror avi · CC BY-SA 3.0',p:'55%'},{t:'探索噴泉山谷',n:'噴泉、水塔、木橋',v:'冒出、濺起、閃避',q:'泉水突然噴出時，附近的人做了甚麼？',img:'Geyser_Gulch.JPG',credit:'Ngchikit · CC BY-SA 3.0',p:'48%'},{t:'漫步西部小鎮',n:'木屋、木牌、礦山',v:'穿過、張望、走近',q:'由街道走向礦山時，景物有甚麼變化？',img:'Hong_Kong_Disneyland_Grizzly_Gulch_201212.JPG',credit:'Wpcpey · CC BY-SA 4.0',p:'40%'}]
];
let score=0,answered=new Set(),route=[],station=0,drafts={},promptLevel=0,player={x:50,y:88},activeExplore=-1,sceneFinds=new Set(),scenePan=0,dragStart=null,activeActivity=-1;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('stepMoveApp',JSON.stringify({route,drafts,essay:$('#essay').value}));$('#saved').textContent='已自動儲存';}
function go(n){$$('.page,.step').forEach(x=>x.classList.toggle('active',+x.dataset.page===n));scrollTo({top:70,behavior:'smooth'});if(n===2)loadStation();if(n===3)buildEssay()}
$$('.step').forEach(b=>b.onclick=()=>go(+b.dataset.page));
function renderQuiz(){$('#quiz').innerHTML=quizData.map((x,i)=>`<div class="question"><b>${i+1}. ${x.q}</b><div class="options">${x.o.map((o,j)=>`<button class="option" data-q="${i}" data-o="${j}">${o}</button>`).join('')}</div><p class="explain hidden" id="ex${i}">${x.e}</p></div>`).join('');$$('.option').forEach(b=>b.onclick=()=>{let i=+b.dataset.q,j=+b.dataset.o;if(answered.has(i))return;answered.add(i);b.classList.add(j===quizData[i].a?'correct':'wrong');b.parentElement.children[quizData[i].a].classList.add('correct');$('#ex'+i).classList.remove('hidden');if(j===quizData[i].a)score++;$('#quizScore').textContent=`${score} / 3`;if(answered.size===3)$('#quizDone').classList.remove('hidden')})}
function renderPlaces(){const order=route.map(x=>x.name),full=route.length>=3;$('#places').innerHTML=spots.map((s,i)=>`<button class="place" data-i="${i}" ${order.includes(s.name)||full?'disabled':''}><span>${s.icon}</span>${s.name}</button>`).join('');$$('.place').forEach(b=>b.onclick=()=>openExplore(+b.dataset.i));$('#routeSlots').innerHTML=route.length?route.map((s,i)=>`<div class="route-item"><b>${i+1}</b>${s.icon} ${s.name}${s.activityTitle?`<small> — ${s.activityTitle}</small>`:''}</div>`).join(''):'<p class="muted" style="color:#607887">從六個園區選擇三個，編排你的遊覽路線吧！</p>';$('#exploreCount').textContent=`已選 ${route.length} / 3 區`;$$('.hotspot').forEach(h=>{let visited=order.includes(spots[+h.dataset.spot].name);h.classList.toggle('visited',visited);h.classList.toggle('unavailable',full&&!visited)})}
function resetPlayer(){player={x:50,y:88};drawPlayer();$('#mapTip').textContent='從入口出發！走近發光圓圈。'}
function addSpot(i,note,activityIndex=-1){if(route.some(s=>s.name===spots[i].name)||route.length>=3)return;let a=activities[i]?.[activityIndex];route.push({...spots[i],mapNote:note,activityIndex,activityTitle:a?.t||'',activityNouns:a?.n||'',actionWords:a?.v||'',activityQuestion:a?.q||'',activityImage:a?.img||'',activityCredit:a?.credit||''});renderPlaces();save();$('#mapTip').textContent=route.length===3?'三區完成！可以按下方按鈕開始寫作。':`已選第 ${route.length} 區，再選 ${3-route.length} 區！`}
$('#clearRoute').onclick=()=>{route=[];renderPlaces();resetPlayer()};$('#routeNext').onclick=()=>{if(route.length!==3){alert('請先從六個園區選定三個。');return}station=0;loadStation();go(2)};
const targets=[{x:50,y:63},{x:22,y:27},{x:77,y:23},{x:82,y:63},{x:16,y:66},{x:48,y:18}];
function drawPlayer(){let a=$('#avatar');a.style.left=player.x+'%';a.style.top=player.y+'%'}
function movePlayer(dx,dy){if(!$('.page[data-page="1"]').classList.contains('active')||!$('#exploreDialog').classList.contains('hidden'))return;player.x=Math.max(5,Math.min(95,player.x+dx));player.y=Math.max(7,Math.min(93,player.y+dy));drawPlayer();if(route.length>=3)return;for(let i=0;i<targets.length;i++){let d=Math.hypot(player.x-targets[i].x,player.y-targets[i].y);if(d<8&&!route.some(s=>s.name===spots[i].name)){openExplore(i);break}}}
function setSceneView(){$('#sceneLayer').style.transform=`translateX(${scenePan}%)`}
function activeSceneObjects(){if(activeActivity<0)return sceneObjects[activeExplore]||[];let a=activities[activeExplore][activeActivity],n=a.n.split('、'),v=a.v.split('、');return [{x:24,y:34,t:'主要景物',n:n[0],q:`${n[0]}的外形、顏色或位置是怎樣的？`},{x:70,y:48,t:'活動細節',n:n[1],q:`人物怎樣「${v[0]}」或「${v[1]}」？`},{x:48,y:72,t:'人物與環境',n:n[2],q:a.q}]}
function renderLookPoints(){let objects=activeSceneObjects();$('#lookPoints').innerHTML=objects.map((o,i)=>`<button class="look-point ${sceneFinds.has(i)?'found':''}" data-object="${i}" style="left:${o.x}%;top:${o.y}%" aria-label="觀察點 ${i+1}">${sceneFinds.has(i)?'✓':'?'}</button>`).join('');$$('.look-point').forEach(b=>b.onclick=e=>{e.stopPropagation();showObject(+b.dataset.object)})}
function showObject(i){let objects=activeSceneObjects(),o=objects[i];if(!o)return;sceneFinds.add(i);$('#objectInfo').innerHTML=`<b>${o.t}</b><span>可用景物名詞：${o.n}</span><em class="object-question">想一想：${o.q}</em>`;let popup=$('#pointPopup');popup.innerHTML=`<b>${o.n}</b><span>想一想：${o.q}</span>`;popup.style.left=Math.max(8,Math.min(64,o.x-12))+'%';popup.style.top=Math.max(8,Math.min(68,o.y+7))+'%';popup.classList.remove('hidden');$('#foundWords').innerHTML=[...sceneFinds].flatMap(n=>objects[n].n.split('、')).map(w=>`<span class="word-chip">${w}</span>`).join('');$('#findCount').textContent=`找到 ${sceneFinds.size} / 3`;renderLookPoints()}
function commonsImage(a){return /^https?:\/\//.test(a.img)?a.img:`https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(a.img)}?width=960`}
function commonsPage(a){return a.page||`https://commons.wikimedia.org/wiki/File:${encodeURIComponent(a.img)}`}
function areaImage(i){return sceneImages[i]||commonsImage(activities[i][0])}
function renderActivities(){let list=activities[activeExplore]||[];$('#activityChoices').innerHTML=list.map((a,i)=>`<div class="activity-card"><button class="activity-choice" data-activity="${i}"><img class="activity-thumb" src="${commonsImage(a)}" alt="${a.t}實景照片" loading="lazy"><b>${a.t}</b><small>${a.n}</small></button><a class="photo-credit" href="${commonsPage(a)}" target="_blank" rel="noopener">相片：${a.credit}</a></div>`).join('');$$('.activity-thumb').forEach(img=>img.onerror=()=>{img.src=sceneImages[activeExplore]||'virtual-park-map.png';img.onerror=null});$$('.activity-choice').forEach(b=>b.onclick=()=>chooseActivity(+b.dataset.activity))}
function chooseActivity(i){activeActivity=i;sceneFinds=new Set();let a=activities[activeExplore][i];$$('.activity-choice').forEach((b,n)=>b.classList.toggle('active',n===i));$('#insideImage').src=commonsImage(a);$('#insideImage').style.objectPosition='50% center';$('#insideImage').onerror=()=>{$('#insideImage').src=sceneImages[activeExplore]||'virtual-park-map.png';$('#insideImage').onerror=null};$('#insideImage').alt=a.t+'實景照片';$('#findCount').textContent='找到 0 / 3';$('#foundWords').innerHTML='';$('#pointPopup').classList.add('hidden');$('#objectInfo').innerHTML=`<b>${a.t}</b><span>可按照片上的發光點查看觀察提示；選區時不用寫句子。</span><div class="action-bank">${a.v.split('、').map(v=>`<span class="action-chip">${v}</span>`).join('')}</div><em class="object-question">想一想：${a.q}</em>`;renderLookPoints()}
function turnScene(delta){scenePan=Math.max(-4,Math.min(4,scenePan+delta));setSceneView()}
function openExplore(i){if(route.length>=3)return;activeExplore=i;activeActivity=-1;sceneFinds=new Set();scenePan=0;$('#dialogIcon').textContent=spots[i].icon;$('#exploreTitle').textContent=spots[i].name;$('#exploreQuestion').textContent='先選擇一項感興趣的活動；發光點可即時顯示觀察提示，這一頁不用寫句子。';$('#findCount').textContent='找到 0 / 3';$('#foundWords').innerHTML='';$('#pointPopup').classList.add('hidden');$('#insideImage').src=areaImage(i);$('#insideImage').onerror=()=>{$('#insideImage').src='virtual-park-map.png';$('#insideImage').onerror=null};$('#insideImage').style.objectPosition='50% center';$('#insideImage').alt=spots[i].name+'的第一身觀察畫面';$('#objectInfo').innerHTML='<b>先選擇下方一項活動</b><span>照片和發光觀察點會一起更新。</span>';setSceneView();renderLookPoints();renderActivities();$('#exploreDialog').classList.remove('hidden')}
function closeExplore(){$('#exploreDialog').classList.add('hidden');activeExplore=-1;activeActivity=-1;$('#parkGame').focus()}
$('#dialogClose').onclick=closeExplore;$('#lookLeft').onclick=()=>turnScene(-2);$('#lookRight').onclick=()=>turnScene(2);
$('#insideScene').addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;dragStart=e.clientX;$('#insideScene').setPointerCapture(e.pointerId)});$('#insideScene').addEventListener('pointermove',e=>{if(dragStart===null)return;let dx=e.clientX-dragStart;if(Math.abs(dx)>8){turnScene(dx>0?-1:1);dragStart=e.clientX}});$('#insideScene').addEventListener('pointerup',()=>dragStart=null);$('#insideScene').addEventListener('pointercancel',()=>dragStart=null);
$('#collectSpot').onclick=()=>{if(activeActivity<0){alert('請先選擇一項活動。');return}addSpot(activeExplore,'',activeActivity);closeExplore()};
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;let dirs={ArrowUp:[0,-2],w:[0,-2],ArrowDown:[0,2],s:[0,2],ArrowLeft:[-2,0],a:[-2,0],ArrowRight:[2,0],d:[2,0]};if(dirs[e.key]){e.preventDefault();movePlayer(...dirs[e.key])}});
$$('.game-controls button').forEach(b=>{let timer;let delta={up:[0,-2],down:[0,2],left:[-2,0],right:[2,0]}[b.dataset.dir];let start=e=>{e.preventDefault();movePlayer(...delta);timer=setInterval(()=>movePlayer(...delta),90)};let stop=()=>clearInterval(timer);b.addEventListener('pointerdown',start);b.addEventListener('pointerup',stop);b.addEventListener('pointerleave',stop);b.addEventListener('pointercancel',stop)});
function currentSpot(){let saved=route[station];let name=typeof saved==='string'?saved:saved?.name;let base=spots.find(x=>x.name===name)||spots[station]||spots[0];return typeof saved==='object'&&saved?{...base,...saved,prompts:base.prompts,hint:base.hint,icon:base.icon}:base}
function showPrompt(){let s=currentSpot(),prompts;if(s.activityTitle){let linked=[[`在「${s.activityTitle}」照片中找出：${s.activityNouns}。`,'由近至遠，景物分別在甚麼位置？','人物正在做甚麼？'],[s.activityQuestion,'哪一個動作最值得詳寫？','你當時可能聽見甚麼或有甚麼感受？'],[`選用動作詞：${s.actionWords}。`,'先用步移詞交代怎樣來到這裏。','把景物、人物動作和感受連成三至四句。']];prompts=linked[promptLevel]}else prompts=s.prompts?.[promptLevel]||['細看畫面：你最先留意到甚麼？'];$('#promptText').innerHTML='<ul>'+prompts.map(x=>`<li>${x}</li>`).join('')+'</ul>';$$('.prompt-tab').forEach(x=>x.classList.toggle('active',+x.dataset.level===promptLevel))}
$$('.prompt-tab').forEach(b=>b.onclick=()=>{promptLevel=+b.dataset.level;showPrompt()});
function stopAtmosphere(){}
function loadStation(){stopAtmosphere();let s=currentSpot();$('#stationName').textContent=s.name;$('#stationIcon').textContent=s.icon;$('#stationHint').textContent=s.hint;let img=$('#sceneStrip');img.classList.toggle('linked-scene',!!s.activityImage);if(s.activityImage){img.src=commonsImage({img:s.activityImage});img.style.transform='none';img.alt=s.activityTitle+'實景照片';img.onerror=()=>{img.src=areaImage(spots.findIndex(x=>x.name===s.name));img.onerror=null}}else{let originalIndex=Math.max(0,spots.findIndex(x=>x.name===s.name));img.src='theme-park-journey.png';img.style.transform=`translateX(-${originalIndex*25}%)`;img.alt=s.name+'觀察畫面';img.onerror=null}$('#linkedActivity').innerHTML=s.activityTitle?`<b>上一頁選擇：${s.activityTitle}</b><span>景物名詞：${s.activityNouns}</span><span>動作詞：${s.actionWords}</span><em>想一想：${s.activityQuestion}</em>`:'<b>這一站未有選擇活動照片</b><span>可按「返回選區」重新選擇。</span>';promptLevel=0;showPrompt();$('#stationCount').textContent=`第 ${station+1} / 3 站`;let d=drafts[station]||{};$('#moveWord').value=d.move||'';$('#scene').value=d.scene||'';$('#action').value=d.action||'';$('#feeling').value=d.feeling||'';$('#prevStation').style.visibility='visible';$('#prevStation').textContent=station?'← 上一站':'← 返回選區';$('#saveStation').textContent=station===2?'完成三站，組合文章 →':'儲存並到下一站 →'}
function storeStation(){drafts[station]={move:$('#moveWord').value,scene:$('#scene').value.trim(),action:$('#action').value.trim(),feeling:$('#feeling').value.trim()};save()}
$('#prevStation').onclick=()=>{if(station===0){go(1);return}storeStation();station--;loadStation()};$('#saveStation').onclick=()=>{if(!$('#moveWord').value||!$('#scene').value.trim()){alert('請至少選擇步移詞，並寫下眼前景物。');return}storeStation();if(station<2){station++;loadStation()}else{buildEssay(true);go(3)}};
function buildEssay(force=false){if($('#essay').value.trim()&&!force)return;let paras=[`星期天，我和家人到迪士尼樂園遊玩。踏進樂園，我滿心期待，準備展開奇妙旅程。`];route.slice(0,3).forEach((s,i)=>{let d=drafts[i]||{};paras.push(`${d.move||'接着，我們來到'}${s.name}。${d.scene||''}${d.action?d.action:''}${d.feeling?d.feeling:''}`)});paras.push('夕陽西下，我們依依不捨地離開樂園。今天沿途看見的景物和快樂回憶，仍深深留在我的腦海中。');$('#essay').value=paras.join('\n\n');save()}
$('#coach').onclick=()=>{const t=$('#essay').value.trim(),moves=['走進','沿着','離開','來到','穿過','轉過','踏進','接着'],senses=['看見','眼前','聽見','傳來','色彩','燈光','音樂','香氣'],feel=['開心','興奮','期待','難忘','不捨','彷彿','感到'];let m=moves.filter(w=>t.includes(w)).length,s=senses.filter(w=>t.includes(w)).length,f=feel.filter(w=>t.includes(w)).length,paras=t.split(/\n\s*\n/).filter(Boolean).length;let praise=m>=3?'你用了多個步移詞，遊覽路線很清楚。':'你已開始按位置寫景，方向是對的。';let challenge=m<3?'再加入「離開……後／沿着……／轉過……」等詞，連接至少三個景點。':s<2?'選一站補寫聲音、顏色或動態，讓讀者像親身看見。':f<2?'不要只說「好玩」，試寫身體反應或聯想，例如「我忍不住歡呼」。':paras<5?'把不同位置分段，每移一步便另起一段。':'挑一個最精彩的景點詳寫，其他景點略寫，文章會更有重點。';$('#feedback').innerHTML=`<div class="feedback-card"><b>我欣賞你</b>${praise}</div><div class="feedback-card"><b>下一步挑戰</b>${challenge}</div><div class="feedback-card"><b>步移檢查</b>找到 ${m} 類移動線索 · ${s} 類感官線索 · ${f} 類感受詞 · ${paras} 段</div>`}
$('#copyEssay').onclick=async()=>{await navigator.clipboard.writeText($('#title').value+'\n\n'+$('#essay').value);$('#copyEssay').textContent='已複製 ✓';setTimeout(()=>$('#copyEssay').textContent='複製文章',1500)};$('#essay').oninput=save;
$('#reset').onclick=()=>{if(confirm('確定清除所有學習進度，重新開始嗎？')){localStorage.removeItem('stepMoveApp');location.reload()}};
let old=null;try{old=JSON.parse(localStorage.getItem('stepMoveApp')||'null')}catch(e){localStorage.removeItem('stepMoveApp')}if(old){route=(old.route||[]).map(item=>{let name=typeof item==='string'?item:item?.name;let base=spots.find(s=>s.name===name);return base?{...base,...(typeof item==='object'?item:{}),prompts:base.prompts}:null}).filter(Boolean).slice(0,3);drafts=old.drafts||{};$('#essay').value=old.essay||'';$('#saved').textContent='已載入並更新上次進度'}
route=route.map(s=>{if(s.activityTitle!=='乘坐魔雪奇幻之旅')return s;let a=activities[4][0];return {...s,activityNouns:a.n,actionWords:a.v,activityQuestion:a.q,activityImage:a.img,activityCredit:a.credit}});
renderQuiz();renderPlaces();
